### ISSUE TITLE
Add support for WebMarkupWin or add support for conditional comments

### ISSUE THREAD

**Issue by 06b** [deanhume/html-minifier#12]
I noticed that the html-minifier removes IE's HTML conditional comments (as highlighted in issue #4) 

Would it be possible to add support to use WebMarkUpWin as it doesn't remove IE's conditional comments as of 0.8.20 - http://webmarkupmin.codeplex.com/workitem/8 or not remove IE conditional comments?

**Comment by 06b** [comment]
My bad, I just saw where in the commit history you have support for conditional comments, I didn't notice it because I was using the exe with the tool folder but it appears it hasn't been updated since those fixes have been applied.

**Comment by deanhume** [comment]
Hi @06b - Thanks for the heads up. I have updated the version and the latest release will contain the code. Check out this link- https://github.com/deanhume/html-minifier/releases/tag/v1.3

**Comment by 06b** [comment]
Sweet, much thanks!
