### ISSUE TITLE
Problem with special characters

### ISSUE THREAD

**Issue by vanderLo** [deanhume/html-minifier#21]
It seems like it has a problem with a couple of German letters: ä, ü, ö, ß
Moreover it can't handle special characters and symbols like: -, ©, etc.

Kind regards
Joe

**Comment by deanhume** [comment]
Hi @vanderLo - what file encoding are you using on the file? I've tried this with multiple encodings and it seems to work. 

Could you please attach a copy of the file that you are using so that I can test it?

**Comment by vanderLo** [comment]
Hi @deanhume - Been using UTF-8. Could this be related to the problem? Anyway, the problem was entirely solved by using the correct HTML Special Entity Codes for ©, ß, ä, ü, ö, § etc.
