### ISSUE TITLE
asp.net expression in markup got changed

### ISSUE THREAD

**Issue by ivanlewis** [deanhume/html-minifier#22]
`<meta` name="copyright" content="<% =settings.websitename %>" />

became 

`<meta` name="copyright" `content="&lt;%` =settings.websitename %>"

**Comment by deanhume** [comment]
Thanks for sending this through - Ill take a look.

**Comment by ivanlewis** [comment]
There is some issues with conversions.. 

₹ changed to â‚¹

I Tried minifying on production server and had to disable it.

**Comment by ivanlewis** [comment]
Original Code:
![snip_20160402131938](https://cloud.githubusercontent.com/assets/835025/14225137/cab7bd5a-f8d5-11e5-89e5-c2086dcb4a5f.png)

After minification:
![snip_20160402131922](https://cloud.githubusercontent.com/assets/835025/14225139/d5cab77e-f8d5-11e5-8be2-d84abb8b863e.png)

**Comment by deanhume** [comment]
Hi @ivanlewis - The latest release seems to be having a few issues with encodings. Please could you upload a copy of the file you are using so that I can build a test around it? 

At the moment it seems to work, but I think it could be due to file. You can attach it to this comment.

**Comment by ivanlewis** [comment]
I had extra spaces there. I removed it and working fine. Will test more and update you.

**Comment by deanhume** [comment]
I'll close this for now. Please let me know if the issue reappears :+1: :+1:

**Comment by ivanlewis** [comment]
Okay sure. Thanks.
