### ISSUE TITLE
Problem with Knockout containerless control flow syntax

### ISSUE THREAD

**Issue by mikilion** [deanhume/html-minifier#23]
The "Knockout" containerless control flow syntax should not be removed from the page.

```
<!-- ko if: someExpressionGoesHere -->
    <li>I want to make this item present/absent dynamically</li>
<!-- /ko -->

```

**Comment by deanhume** [comment]
@mikilion - I'm thinking about the best way to work around this as there may be other JavaScript tools that require similar style comments. I am thinking of adding an **ignoreHtmlComments** flag - would this work for your issue?

**Comment by mikilion** [comment]
@deanhume - Ignoring custom comments option by regular expression is a good idea.

**Comment by deanhume** [comment]
This has been fixed with the [latest commit](https://github.com/deanhume/html-minifier/commit/64091915046d64f55539dbde238ac8bb63f5df64) and will go out as part of Release 1.8

**Comment by mikilion** [comment]
The "ignoreknockoutcomments" argument  doesn't work on 1.9 version.
I tried to modify following regular expression:
`<!--(?!\[)(?!ko .*)(?!\/ko)(.*?)-->`
in this:
`<!--(?!ko .*)(?!\/ko)-->`
at line 164 of the class "StreamReaderExtension".

Awaiting your feed back
