### ISSUE TITLE
problems with html files that contain unicode characters

### ISSUE THREAD

**Issue by HassanHashemi** [deanhume/html-minifier#28]
it seems that there is a problem with unicode chars. to fix this you just need to modify Program.cs and add this: "File.WriteAllText(filePath, minifiedContents, Encoding.UTF8);"

**Comment by deanhume** [comment]
Hi - thanks for logging this. I will take a look into it and get back to you!

**Comment by MiroRadenovic** [comment]
here you go: https://github.com/deanhume/html-minifier/pull/32

**Comment by deanhume** [comment]
This has been merged into the latest source thanks to @MiroRadenovic - [fix](https://github.com/deanhume/html-minifier/pull/32)
