### ISSUE TITLE
<input type="file" accept="image/*" name="files[]" multiple>

### ISSUE THREAD

**Issue by yangar** [deanhume/html-minifier#36]
Look like the following code can't be minified:
`                                <input type="file" accept="image/*" name="files[]" multiple>`
HtmlMinifier.exe stop to do the job when it see this line of code.

**Comment by heldersepu** [comment]
Not sure what you mean by **"stop to do the job"** ...
Do you get an error?

I did the following test:

```html
<div class="row">
    <div class="col-md-12">
        <div class="data-block">
            <input type="file" accept="image/*" name="files[]" multiple>
        </div>
    </div>
</div>
```
And it mini(ed) fine to:
```html
<div class="row"><div class="col-md-12"><div class="data-block"><input type="file" accept="image/*" name="files[]" multiple></div></div></div>
```

Can you upload a sample file?

**Comment by Deutschi** [comment]
The following sample either takes a really long time or doesn't finish at all:

```
<div id="foo">
	<div class="foo">
		<i class="foo"></i>
		<input id="file" name="file" type="file" accept="image/*" class="foo" autocomplete="off" />

		<span id="foo" class="foo">
		
		</span>

		<div id="foo" class="foo">
			
		</div>
	</div>
	<div id="foo" class="foo">
		<i class="foo"></i>
	</div>
</div>
```

The empty lines are important however. If I remove them by myself, the minification finishes (it takes a few seconds though):

```
<div id="foo">
	<div class="foo">
		<i class="foo"></i>
		<input id="file" name="file" type="file" accept="image/*" class="foo" autocomplete="off" />
		<span id="foo" class="foo">
		</span>
		<div id="foo" class="foo">
		</div>
	</div>
	<div id="foo" class="foo">
		<i class="foo"></i>
	</div>
</div>
```

**Comment by heldersepu** [comment]
@Deutschi
I was able to reproduce it:
https://github.com/heldersepu/html-minifier/commit/34687512078fd120b055e14a564ae16f310e1619

**Comment by deanhume** [comment]
This has been fixed in the latest [PR](https://github.com/deanhume/html-minifier/pull/40) courtesy of @heldersepu
