### ISSUE TITLE
Razor text mode does not minify properly

### ISSUE THREAD

**Issue by reZach** [deanhume/html-minifier#42]
When including html that has this, the minification does not properly account for this (I believe razor needs the **@:** on a single line by itself, minifying the html causes an error).

I somehow can't get read access to this repository, but you'll need the following code in StreamReaderExtension.cs to fix this:

`// Replace Razor "@:" (text mode) instances`
`htmlContents = Regex.Replace(htmlContents, @"@:\s", "{{{TEXT_MODE}}}");`

Further below....
`htmlContents = htmlContents.Replace("{{{TEXT_MODE}}}", "\r\n@:\r\n");`

**Comment by Deutschi** [comment]
This looks like the same issue that got resolved [here](https://github.com/deanhume/html-minifier/issues/24) a few hours ago. Should be working in the latest release.

**Comment by deanhume** [comment]
This should be fixed in the latest release - closing for now!
