### ISSUE TITLE
minify js file encode error

### ISSUE THREAD

**Issue by wyp315360007** [deanhume/html-minifier#43]
services.AddWebMarkupMin(
                    options =>
                    {
                        options.AllowMinificationInDevelopmentEnvironment = true;
                        options.AllowCompressionInDevelopmentEnvironment = true;
                    })
                .AddHtmlMinification(
                    options =>
                    {
                        options.MinificationSettings.RemoveRedundantAttributes = true;
                        options.MinificationSettings.RemoveHttpProtocolFromAttributes = true;
                        options.MinificationSettings.RemoveHttpsProtocolFromAttributes = true;
                        options.MinificationSettings.RemoveTagsWithoutContent = true;
                        options.MinificationSettings.MinifyEmbeddedJsCode = true;
                        options.MinificationSettings.MinifyEmbeddedCssCode = true;
                    })
                .AddHttpCompression();

app.UseWebMarkupMin();`

js file content with chinese char show error in browser

![image](https://user-images.githubusercontent.com/3982847/29696210-02681bf6-897a-11e7-96fa-b9416bfa6b96.png)
file encode with utf-8 without bom

**Comment by deanhume** [comment]
This issue is fixed in the latest release!
