### ISSUE TITLE
Issue with accents in words

### ISSUE THREAD

**Issue by bacvothanh** [deanhume/html-minifier#44]
There is problem with accents in words.
I'm using Asp.net MVC, and when try to use html-minifier, some words on my website display are incorrect.
Example :  
`<h4><i class="fa fa-play-circle-o"></i>Xem gì hôm nay?</h4>`
-->
`<h4><i class="fa fa-play-circle-o"></i>Xem gÃ¬ hÃ´m nay?</h4>`
Please help me how to fix it

**Comment by deanhume** [comment]
This should be fixed in the latest release!

https://github.com/deanhume/html-minifier/blob/7208672c9763b442436ffc049c70731ca04dac48/HtmlMinifier.Tests/DataHelpers.cs#L109
