### ISSUE TITLE
Multiple * Bug

### ISSUE THREAD

**Issue by justlearntutors** [deanhume/html-minifier#51]
The job is loading for a very long time or it doesn't complete.

I read https://github.com/deanhume/html-minifier/issues/36, but it is not working.

My code
`<input accept="image/*" />
<input accept="image/*" />
<input accept="image/*" />
<input accept="image/*" />
<input accept="image/*" />
<input accept="image/*" />
<div>
    <div>
        @if (true)
        {

        }
        else
        {

        }
    </div>
</div>`

**Comment by justlearntutors** [comment]
```
<input accept="image/*" />
<input accept="image/*" />
<input accept="image/*" />
<input accept="image/*" />
<input accept="image/*" />
<input accept="image/*" />
<div>
    <div>
        @if (true)
        {

        }
        else
        {

        }
    </div>
</div>
```

**Comment by deanhume** [comment]
Hi - are you sure you have the latest version of the exe? 

https://github.com/deanhume/html-minifier/releases/tag/v1.9.1

This seems to work for me - please feel free to re-open this issue if you are still experiencing
