### ISSUE TITLE
utf8

### ISSUE THREAD

**Issue by MohammadReza10** [deanhume/html-minifier#52]
no support utf8 character
(arabic language)

**Comment by deanhume** [comment]
I've added the following [test ](https://github.com/deanhume/html-minifier/blob/38442326b85fdcf0e713c17fb03d35dd27bb3a94/HtmlMinifier.Tests/MinificationTests.cs#L250) to check for Arabic support and it seems to work for me.

Does this look right to you? If so, Ill close this issue!
