### ISSUE TITLE
Encoding error for accept tag in input type file.

### ISSUE THREAD

**Issue by ivanlewis** [deanhume/html-minifier#54]
<input id="fuFileUploadAsync" class="file-upload-async" type="file" accept="application/pdf,image/*" />

When I remove accept="application/pdf,image/*" it is working else minification stops.

**Comment by deanhume** [comment]
This has now been fixed and tests have been written for it. 

Please see the latest release for more info - https://github.com/deanhume/html-minifier/releases/tag/v1.9.2
