### ISSUE TITLE
Issue with non-standard characters

### ISSUE THREAD

**Issue by martonx** [deanhume/html-minifier#8]
Hi,

First of all, HTML minifier is a very good stuff. But my page's language is hungarian, and the minifier brokes all of the hungarian specific characters like ÁÉŐÓÜ....

Could you solve this issue?

**Comment by deanhume** [comment]
Hi @martonx This issue has been resolved with the latest release (https://github.com/deanhume/html-minifier/releases/tag/v1.3). I've also added unit tests to confirm that language specific characters work - please see the latest commit for more detail (https://github.com/deanhume/html-minifier/commit/a4ad93761168be890e268992af12e576c51a42df). Thank you!

**Comment by martonx** [comment]
Thank you very much!
